academy_control/urls.py
from django.conf.urls import url

from academy_control import views

app_name = 'academy_control'

urlpatterns = [
    url(r'^massage/',views.check_stu_massage,name='control_stu_mas'),
    url(r'^detil/(\w+)/',views.detil_massage,name='show_detil'),
]

django_auth_example/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from users import views
from student import views as s_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^academy/',include('academy_control.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^student_massage_add/',s_views.index,name='ma_add'),
    url(r'^student_massage_show/',s_views.student_massage_page,name='stu_page'),
    url(r'^parents_massage_add/',s_views.parents_page_commit,name='Pmas_add'),
    url(r'^update_add/',s_views.update_page_add,name='up_add'),
    url(r'^gratuated_add',s_views.gratuate_page_add,name='gr_add'),
    url(r'^parents_massage_show/',s_views.parents_page,name='p_show'),
    url(r'^update_show/',s_views.update_page,name='up_show'),
    url(r'^gratuated_show/',s_views.gratuate_page,name='gr_show')
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
]

templates/base.html
<!DOCTYPE html>
<html lang="zh-han">
<head>
    {% load static %}
	<title>注册</title>
	<!-- meta-tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="" />
	<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
	<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link href="/static/css/font-awesome.css" rel="stylesheet">
</head>

<body>
	<!-- header -->
	<div class="header-top">
		<div class="container">
			<div class="bottom_header_left">
				<p>
					<span class="fa fa-map-marker" aria-hidden="true"></span>长春, CHINA
				</p>
			</div>
			<div class="bottom_header_right">
				<div class="header-top-righ">
					<a href="{% url 'login' %}">
						<span class="fa fa-sign-out" aria-hidden="true"></span>登录</a>
				</div>

				<div class="header-top-righ">
                    <a href="{% url 'logout' %}">
                        <span class="fa fa-sign-out">注销</span>
                    </a>
                </div>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	<div class="header">
		<div class="content white">
			<nav class="navbar navbar-default">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="index.html">
							<h1>
								<span class="fa fa-leanpub" aria-hidden="true"></span>长春工业大学
								<label>少数民族学生信息管理系统</label>
							</h1>
						</a>
					</div>
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<nav class="link-effect-2" id="link-effect-2">
							<ul class="nav navbar-nav">
								<li>
									<a href="{% url 'index' %}" class="effect-3">主页</a>
								</li>
								<li>
									<a href="{% url 'stu_page' %}" class="effect-3">个人信息</a>
								</li>
								<li>
									<a href="{% url 'p_show' %}" class="effect-3">家庭信息</a>
								</li>
								<li>
									<a href="{% url 'up_show' %}" class="effect-3">年度信息</a>
								</li>
								<li>
									<a href="{% url 'gr_show' %}" class="effect-3">毕业就业</a>
								</li>
								<li>
									<a href="{% url 'academy_control:control_stu_mas' %}" class="effect-3">辅导员界面</a>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</nav>
		</div>
	</div>
	<div class="inner_page_agile">

	</div>
	<div class="services-breadcrumb">
		<div class="inner_breadcrumb">
			<ul class="short_ls">
				<li>
					<a href="index.html">Home</a>
					<span>| |</span>
				</li>
				<li>Register</li>
			</ul>
		</div>
	</div>
	<div class="register-form-main">
        {% block content%}
		<div class="container">
			<div class="title-div">
				<h3 class="tittle">
					<span>R</span>egister
					<span>F</span>orm
				</h3>
				<div class="tittle-style">

				</div>
			</div>
			<div class="login-form">
				<form action="#" method="post">
					<div class="">
						<p>学号 </p>
						<input type="text" class="name" name="user name" required="" />
					</div>
					<div class="">
						<p>邮箱</p>
						<input type="email" class="password" name="email" required="" />
					</div>
					<div class="">
						<p>密码</p>
						<input type="password" class="password" name="Password" id="password1" required="" />
					</div>
					<div class="">
						<p>确认密码</p>
						<input type="password" class="password" name="Password" id="password2" required="" />
					</div>
					<label class="anim">
						<input type="checkbox" class="checkbox">
						<span>I Accept Terms & Conditions</span>
					</label>
					<input type="submit" value="Register">
				</form>
			</div>
		</div>
        {% endblock %}
	</div>
	<div class="mkl_footer">
		<div class="sub-footer">
			<div class="container">
				<div class="mkls_footer_grid">
					<div class="col-xs-4 mkls_footer_grid_left">
						<h4>Location:</h4>
						<p>延安大街2055号长春工业大学,
							<br> 长春, CHINA</p>
					</div>
					<div class="col-xs-4 mkls_footer_grid_left">
						<h4>Mail Us:</h4>
						<p>
							<span>Phone : </span>001 234 5678</p>
						<p>
							<span>Email : </span>
							<a href="mailto:info@example.com">mail@example.com</a>
						</p>
					</div>
					<div class="col-xs-4 mkls_footer_grid_left">
                        <h4>Created by:</h4>
						<p>计算机科学与工程学院</p>
						<p>
							<span><a href="https://github.com/541573560">harry</a>&<a href="https://github.com/JackJinSong">Jack jin song</a></span>
						</p>>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="botttom-nav-allah">
				</div>
				<div class="footer-middle-thanks">
					<h2>长春工业大学学生处</h2>
				</div>
			</div>
		</div>

	</div>
	<script src="/static/js/jquery-2.1.4.min.js"></script>
	<script src="/static/js/bootstrap.js"></script>
	<script src="/static/js/SmoothScroll.min.js"></script>
	<script src="/static/js/move-top.js"></script>
	<script src="/static/js/easing.js"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="title-div">
    <h3 class="tittle">
        <span>W</span>elcome
    </h3>
    <div class="tittle-style">

    </div>
</div>
<div class="login-form">
    <div class="welcome" style="margin-left: 35%" >
    {% if user.is_authenticated %}
    <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
    <button class="btn btn-default"><a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
    </button>
    <button class="btn btn-default"><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
    </button>
{% else %}
    <p>你还没有登录，请
        <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a>
        </button>
        或者
        <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a>
        </button>
    </p>
    {% endif %}
    </div>
</div>
{% endblock %}